# 开发环境配置

# 数据源配置
spring:
  datasource:
    master:
      url: jdbc:mysql://localhost:3306/db_asuka?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

# 日志配置
logging:
  level:
    com.asuka: DEBUG
