# 端口
server:
  port: 8031
  servlet:
    context-path:

# 多环境配置
spring:
  profiles:
    active: dev

  # json时间格式设置
  jackson:
    time-zone: GMT+8
    date-format: yyyy/MM/dd HH:mm:ss

  # 设置上传文件大小
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  # 邮件服务器配置
  mail:
    host: smtp.qq.com
    username:
    password:
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465

