# 开发环境配置

# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_asuka?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 1qaz2wsx
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

# 日志配置
logging:
  level:
    com.asuka: DEBUG
    com.baomidou.mybatisplus: DEBUG
