# 开发环境配置

# 数据源配置
spring:
  datasource:
    master:
      url: jdbc:mysql://111.229.123.213:3306/db_asuka?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
      username: db_asuka
      password: EE7Ftc3JRXKSsXh2
      driver-class-name: com.mysql.cj.jdbc.Driver

# 日志配置
logging:
  level:
    com.asuka: DEBUG
