# 生产环境配置

server:
  port: 8088

# 数据源配置
spring:
  datasource:
    master:
      # 建议填写局域网ip
      url: jdbc:mysql://127.0.0.1:3306/db_asuka?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
      username: db_asuka
      password: EE7Ftc3JRXKSsXh2
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    # Redis 数据库索引（默认为 0）
    database: 0
    # Redis 服务器连接密码（默认为空）
    password:

# 日志配置
logging:
  file:
    name: asuka.log
  level:
    root: WARN
    com.asuka: ERROR
