# 开发环境配置

# 数据源配置
spring:
  datasource:
    master:
<<<<<<< HEAD
      url: jdbc:mysql://localhost:3306/db_asuka?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: root
=======
      url: jdbc:mysql://111.229.123.213:3306/db_asuka?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
      username: db_asuka
      password: EE7Ftc3JRXKSsXh2
>>>>>>> b09d1fac8d048da5753145fd10decdce65c2143b
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    # Redis 数据库索引（默认为 0）
    database: 0
    # Redis 服务器连接密码（默认为空）
    password:


# 日志配置
logging:
  level:
    com.asuka: DEBUG
