# 端口
server:
  port: 8031
  servlet:
    context-path:

# 多环境配置
spring:
  profiles:
    active: dev

  # json时间格式设置
  jackson:
    time-zone: GMT+8
    date-format: yyyy/MM/dd HH:mm:ss

  # 设置上传文件大小
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  # 邮件服务器配置
  mail:
    host: smtp.qq.com
    username:
    password:
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

# 定时任务配置
job:
  # 类型选择：XXL/Quartz，如果不填则默认为Quartz
  type: Quartz

# xxl-job - 分布式任务调度平台 配置 appname 为项目名
xxl:
  job:
    accessToken:
    executor:
      appname: asuka-job
      ip:
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 8099
      address:
    admin:
      addresses: http://localhost:8080/xxl-job-admin